### PR TITLE
Added pre-watching icon of app in commands "launch" and "uninstall"

### PR DESCRIPTION
**Pull request by Anready**
idk if it needs, but i need this function

### CODE REVIEW

**Comment by coderGtm** [comment]
What's it about?

**Comment by Anready** [comment]
let me show you as video

https://github.com/coderGtm/yantra-app-launcher/assets/104269567/f4c6b09a-ce72-4442-9307-d18fcc7ef304

**Comment by Anready** [comment]
this is long-press

**Comment by coderGtm** [comment]
ICONS ?????????

**Comment by coderGtm** [comment]
Noooo

**Pull request closed without merging**
