### PR TITLE
Document `search` Command

### PR DESCRIPTION
**Pull request by eeriemyxi**
> [!IMPORTANT]  
> I had to add a few features to your `mkdocs.yml` file.

Document the `search` command under `docs/commands/search.md`.

### CODE REVIEW

**Comment by coderGtm** [comment]
The -u flag is for URL instead of "unknown"

**Comment by eeriemyxi** [comment]
There are two more issues:

- The URL for alias hyperlink assumes /commands as the first path but your documentation is hosted under /yantra-app-launcher.

It is resolved if you get a free domain from http://pages.dev or replace /commands with /yantra-app-launcher/commands

- After the "Example:" text of -u flag there should be a new line. Without it the list will not render.


@coderGtm

**Comment by coderGtm** [comment]
Fixed!

**Comment by coderGtm** [comment]
I am not sure if pages.dev is right as it has been marked suspicious by many due to extensive use for phishing

**Pull request merged**
