### PR TITLE
Ukrainian translation 

### PR DESCRIPTION
**Pull request by Vika505**

### CODE REVIEW

**Comment by coderGtm** [comment]
Shall I merge it? I have checked that the number is correct however cant verify the correctness of translations. Can you confirm that it is fit for release and free of anything that can harm a person/organization/caste/country/ethnicity/race?

Sounds stupid but I needa do this...

**Comment by Vika505** [comment]
Now, yes

**Comment by Anready** [comment]
@coderGtm yes, if something is wrong, i take the blame

**Comment by Anready** [comment]
@coderGtm yes, if something is wrong, i take the blame

**Review by Anready — APPROVED** [review]

**Pull request merged**
