### PR TITLE
Speed-up call

### PR DESCRIPTION
**Pull request by Anready**
https://github.com/user-attachments/assets/21df8bd1-9ea9-4a31-b95f-24d339d309a5

### CODE REVIEW

**Comment by coderGtm** [comment]
Damn that looks INSANE!!!

I won't be able to go through the code rn but will check it out at night. Can you explain the changes you made by then?

**Comment by Anready** [comment]
initially I tried to do it through multithreading, but it didn't work, and I reduced the number of requests, made a hashmap, the speed increased 3 times

**Comment by Anready** [comment]
initially I tried to do it through multithreading, but it didn't work, and I reduced the number of requests, made a hashmap, the speed increased 3 times

**Review by coderGtm — APPROVED** [review]

**Comment by coderGtm** [comment]
mind-blowing.....

**Comment by coderGtm** [comment]
Fixes #100 in the best possible way!

**Pull request merged**
