### PR TITLE
Added "Suggestion Bar Color" Setting to Custom Theme Dialog

### PR DESCRIPTION
**Pull request by KevinFerryJr**
Custom colors can be selected for the background of suggestions through the custom theme dialog window.

### CODE REVIEW

**Comment by Anready** [comment]
wait, i can change bg color of suggestions

**Comment by KevinFerryJr** [comment]
> wait, i can change bg color of suggestions
> 

Wait really, how? I only see a setting for the "Suggestions Color" for changing the color of the text itself.

**Comment by Anready** [comment]
let me check

**Comment by Anready** [comment]
Background Color (first)

**Comment by KevinFerryJr** [comment]
> Background Color (first)
> 

Ah i think i see what you mean, If you have a wallpaper the only visible effect of changing "Background Color" is that the suggestion backgrounds change to the selected color. If you dont have a wallpaper on however you dont have control over the terminal background color and the suggestion background color individually.

**Comment by Anready** [comment]
> > Background Color (first)
> 
> Ah i think i see what you mean, If you have a wallpaper the only visible effect of changing "Background Color" is that the suggestion backgrounds change to the selected color. If you dont have a wallpaper on however you dont have control over the terminal background color and the suggestion background color individually.

Yes

**Review by coderGtm — APPROVED** [review]

**Pull request merged**
